apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway