apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}-gateway
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "k8s.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      serviceAccountName: {{ template "k8s.serviceAccountName" . }}
      containers:
        - name: {{ include "k8s.fullname" . }}-gateway
          image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8999
              protocol: TCP