apiVersion: v1
kind: Service
metadata:
  name: hotrod
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: hotrod
{{- if .Values.hotrod.service.annotations }}
  annotations:
    {{- toYaml .Values.hotrod.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.hotrod.service.type }}
  ports:
    - name: http
      port: {{ .Values.hotrod.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: hotrod