apiVersion: v1
kind: Service
metadata:
  name: otel
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.otel.service.type }}
  ports:
    {{- range $key, $port := .Values.otel.ports }}
    - name: {{ $key }}
      port: {{ $port.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $port.protocol }}
    {{- end }}
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
    component: standalone-collector